title: Mao Kimlang
logo: circle.png
description: A highly motivated senior data science student passionate about leveraging data to solve real-world problems. My goal is to uncover actionable insights that drive business growth and innovation. 
theme: minimal
author:
  name: Mao Kimlang
  email: your.email@example.com
welcome_message: "Welcome to my portfolio!"
