title: Mao Kimlang
logo: circle.png
description: A highly motivated **senior data science student** passionate about leveraging data to solve real-world problems. Eager to thrive in fast-paced, data-driven environments, I specialize in **data analysis, machine learning, and data visualization**. My goal is to uncover actionable insights that drive business growth and innovation.
show_downlaods: true
theme: jekyll-theme-minimal
