title: Welcome to my portfolio
name: Mao Kimlang
email: kimlangmao82@gmail.com
logo: circle.png
description: A highly motivated senior data science student passionate about leveraging data to solve real-world problems. My goal is to uncover actionable insights that drive business growth and innovation. 
theme: jekyll-theme-minimal
